--1.
SELECT STUDENT_NO,STUDENT_NAME,ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;

--2.
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___'
ORDER BY PROFESSOR_NAME;

--3.
SELECT PROFESSOR_NAME 교수이름,TRUNC((SYSDATE-TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6)))/365) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) IN ('1','3')
ORDER BY "나이" ASC;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE (EXTRACT(YEAR FROM ENTRANCE_DATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6)))) NOT IN(18,19)
ORDER BY STUDENT_NAME;


SELECT TO_DATE(SUBSTR(STUDENT_SSN,1,2))
FROM TB_STUDENT;
--6.
SELECT TO_CHAR(2020-12-25, 'DAY'),
       TO_CHAR('2020/12/25', 'DY')
FROM DUAL;

--7.


--8.
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%';

--9.
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO ='A517178';

--10.
SELECT DEPARTMENT_NO 학과번호,COUNT(*)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO,1,4) 년도,ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO='A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

--13.
SELECT DEPARTMENT_NO 학과코드명,COUNT(*) AS "휴학생"
FROM TB_STUDENT
WHERE ABSENCE_YN='Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME AS "동일이름",COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>=2
ORDER BY STUDENT_NAME;

--15.
SELECT SUBSTR(TERM_NO,1,4) AS "년도",SUBSTR(TERM_NO,5,2) AS "학기",ROUND(POINT,1)
FROM TB_GRADE
WHERE STUDENT_NO='A112113';



