--1. 70년대 생(1970~1979) 중 여자이면서 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회
SELECT EMP_NAME,EMP_ID,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE SUBSTR(EMP_NO,1,1)='7' AND SUBSTR(EMP_NO,8,1)IN ('2','4') AND EMP_NAME LIKE '전%';

--3. 이름에 ‘형’이 들어가는 사원의 사원 코드, 사원 명, 직급 조회  
SELECT EMP_ID,EMP_NAME,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

--4. 부서코드가 D5이거나 D6인 사원의 사원 명, 직급 명, 부서 코드, 부서 명 조회
SELECT EMP_NAME 사원명,JOB_NAME 직급명,DEPT_CODE 부서코드,DEPT_TITLE 부서명
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE DEPT_CODE IN ('D5','D6');

--5. 보너스를 받는 사원의 사원 명, 부서 명, 지역 명 조회
SELECT EMP_NAME,DEPT_TITLE,LOCAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN LOCATION ON(LOCATION_ID=LOCAL_CODE)
WHERE BONUS IS NOT NULL;

--6. 사원 명, 직급 명, 부서 명, 지역 명 조회
SELECT EMP_NAME 사원명,JOB_NAME 직급명,DEPT_TITLE 부서명,LOCAL_NAME 지역명
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN LOCATION ON (LOCATION_ID=LOCAL_CODE);

--7. 한국이나 일본에서 근무 중인 사원의 사원 명, 부서 명, 지역 명, 국가 명 조회
SELECT EMP_NAME 사원명,DEPT_TITLE 부서명,LOCAL_NAME 지역명,NATIONAL_NAME 국가명
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE=DEPT_ID)
JOIN LOCATION ON (LOCATION_ID=LOCAL_CODE)
JOIN NATIONAL USING(NATIONAL_CODE);

--8. 한명의 사원과 같은 부서에서 일하는 사원의 이름 조회(자체조인 활용)
SELECT M.EMP_NAME,E.EMP_NAME,E.DEPT_CODE
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M ON(E.DEPT_CODE=M.DEPT_CODE)
WHERE E.DEPT_CODE=M.DEPT_CODE AND E.EMP_NAME!=M.EMP_NAME;

SELECT E.EMP_NAME,E.DEPT_CODE,D.EMP_NAME
FROM EMPLOYEE E
JOIN EMPLOYEE D ON(E.DEPT_CODE=D.DEPT_CODE)
WHERE E.EMP_ID!=D.EMP_ID
ORDER BY E.EMP_ID;

--9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명, 급여 조회(NVL 이용)
SELECT EMP_NAME 사원명 ,JOB_NAME 직급명,SALARY 급여
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE JOB_CODE IN ('J4','J7') AND BONUS IS NULL;
--10. 부서 명과 부서 별 급여 합계 조회
SELECT DEPT_TITLE,SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE=DEPT_ID)
GROUP BY DEPT_TITLE;
--11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서 명, 부서 별 급여 합계 조회
SELECT DEPT_TITLE,SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
GROUP BY DEPT_TITLE
HAVING SUM(SALARY)>(SELECT SUM(SALARY)
                        FROM EMPLOYEE)*0.2;
                                      
--12. 나이 상 가장 막내의 사원 코드, 사원 명, 나이, 부서 명, 직급 명 조회
SELECT *
FROM(SELECT EMP_ID 사원코드,EMP_NAME 사원명,TRUNC((SYSDATE-TO_DATE(SUBSTR(EMP_NO,1,6)))/365) AS "나이",DEPT_TITLE 부서명,JOB_NAME 직급명
        FROM EMPLOYEE
        JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
        JOIN JOB USING(JOB_CODE)
        ORDER BY 나이)
WHERE ROWNUM<=1;

SELECT EMP_ID,EMP_NAME,TRUNC((SYSDATE-TO_DATE(SUBSTR(EMP_NO,1,6)))/365) AS "나이",DEPT_TITLE,JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE TRUNC((SYSDATE-TO_DATE(SUBSTR(EMP_NO,1,6)))/365)=(SELECT MIN(TRUNC((SYSDATE-TO_DATE(SUBSTR(EMP_NO,1,6)))/365))
                                                        FROM EMPLOYEE);


