CREATE TABLE RENTARRAY (
    BOOKNUMBER INT NOT NULL,  -- 책 번호 (외래키로 사용)
    MEMBERNO INT NOT NULL,  -- 회원 번호 (외래키로 사용)
    BOOKNAME VARCHAR(50) NOT NULL,  -- 책 제목
    BOOKAUTHOR VARCHAR(50) NOT NULL,  -- 저자
    PRIMARY KEY (BOOKNUMBER, MEMBERNO),  -- 책 번호와 회원 번호를 복합 기본키로 설정
    FOREIGN KEY (BOOKNUMBER) REFERENCES BOOK(BOOKNUMBER),  -- 책 번호 외래키
    FOREIGN KEY (MEMBERNO) REFERENCES MEMBER(MEMBERNO)  -- 회원 번호 외래키
);
DROP TABLE BOOK;

CREATE TABLE BOOK (
    BOOKNUMBER NUMBER PRIMARY KEY,
    BOOKNAME VARCHAR2(50) NOT NULL,
    BOOKAUTHOR VARCHAR2(50) NOT NULL
);
INSERT INTO BOOK VALUES( 

CREATE SEQUENCE SEQ_BOOKNUMBER
NOCACHE;



CREATE TABLE MEMBER( 
    MEMBERNO NUMBER PRIMARY KEY, 
    MEMBERID VARCHAR2(50) NOT NULL, 
    MEMBERPASSWORD VARCHAR2(50) NOT NULL, 
    MEMBERNAME VARCHAR2(10) NOT NULL 
);


CREATE SEQUENCE SEQ_MEMBERNO
NOCACHE;

CREATE TABLE ROOTMEMBER (
ROOTMEMBERID VARCHAR2(30) NOT NULL,
ROOTMEMBERPASSWORD VARCHAR2(30) NOT NULL
);

INSERT INTO ROOTMEMBER VALUES('ROOT','ROOT');
COMMIT;





